# Generated by Django 5.2 on 2025-05-28 21:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=150)),
                ('integrantes', models.CharField(max_length=150)),
                ('objetivo', models.TextField()),
                ('imagen', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=30)),
                ('institucion', models.CharField(max_length=150)),
                ('anoAcademico', models.CharField(max_length=4)),
                ('adecuacion', models.CharField(max_length=40)),
                ('tipoAdecuacion', models.CharField(max_length=80)),
                ('beca', models.CharField(max_length=10)),
                ('montoBeca', models.CharField(max_length=30)),
                ('institucionBeca', models.CharField(max_length=80)),
                ('comentario', models.TextField(blank=True, max_length=600, null=True)),
                ('adjuntoNotas', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaNacimiento', models.DateField()),
                ('Edad', models.CharField(max_length=3)),
                ('cedula', models.CharField(max_length=20)),
                ('telefono1', models.CharField(max_length=30)),
                ('telefono2', models.CharField(max_length=30)),
                ('lugarResidencia', models.CharField(max_length=300)),
                ('lesiones', models.CharField(max_length=300)),
                ('enferemedades', models.CharField(max_length=300)),
                ('trataminetos', models.CharField(max_length=300)),
                ('atencionMedica', models.CharField(max_length=400)),
                ('drogas', models.CharField(max_length=200)),
                ('disponibilidad', models.CharField(max_length=400)),
                ('casa', models.CharField(max_length=100)),
                ('montoCasa', models.CharField(max_length=100)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('comentario4', models.TextField(blank=True, null=True)),
                ('Trabaja', models.CharField(max_length=100)),
                ('Empresa', models.CharField(max_length=100)),
                ('salario', models.CharField(max_length=200)),
                ('comentario5', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('edad2', models.CharField(max_length=4)),
                ('parentesco', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=400)),
                ('ingresoMensual', models.CharField(max_length=400)),
                ('lugarTrabajo', models.CharField(max_length=400)),
                ('ingresos', models.CharField(max_length=400)),
                ('salario2', models.CharField(max_length=400)),
                ('pension', models.CharField(max_length=400)),
                ('beca2', models.CharField(max_length=400)),
                ('gastos', models.CharField(max_length=400)),
                ('comida', models.CharField(max_length=400)),
                ('agua', models.CharField(max_length=400)),
                ('luz', models.CharField(max_length=400)),
                ('internetCable', models.CharField(max_length=400)),
                ('celular', models.CharField(max_length=400)),
                ('viaticos', models.CharField(max_length=400)),
                ('salud', models.CharField(max_length=400)),
                ('deudas', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('sede', models.CharField(blank=True, max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, max_length=150, null=True)),
                ('genero', models.CharField(max_length=10)),
                ('sede', models.CharField(max_length=150)),
                ('cometario1', models.TextField(blank=True, null=True)),
                ('cometario2', models.TextField(blank=True, null=True)),
                ('cometario3', models.TextField(blank=True, null=True)),
                ('fechaExpediente', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
