# Generated by Django 5.2 on 2025-05-21 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Atletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=30)),
                ('institucion', models.CharField(max_length=150)),
                ('anoAcademico', models.CharField(max_length=30)),
                ('adecuacion', models.CharField(max_length=30)),
                ('tipoAdecuacion', models.CharField(max_length=30)),
                ('beca', models.CharField(max_length=30)),
                ('montoBeca', models.CharField(max_length=30)),
                ('institucionBeca', models.CharField(max_length=30)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('adjuntoNotas', models.FileField(blank=True, null=True, upload_to='notas/')),
                ('fechaNacimiento', models.DateField()),
                ('Edad', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=30)),
                ('telefono1', models.CharField(max_length=30)),
                ('telefono2', models.CharField(max_length=30)),
                ('lugarResidencia', models.CharField(max_length=30)),
                ('lesiones', models.CharField(max_length=400)),
                ('enferemedades', models.CharField(max_length=400)),
                ('trataminetos', models.CharField(max_length=400)),
                ('atencionMedica', models.CharField(max_length=400)),
                ('drogas', models.CharField(max_length=400)),
                ('disponibilidad', models.CharField(max_length=400)),
                ('casa', models.CharField(max_length=400)),
                ('montoCasa', models.CharField(max_length=400)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('comentario4', models.TextField(blank=True, null=True)),
                ('Trabaja', models.CharField(max_length=400)),
                ('Empresa', models.CharField(max_length=400)),
                ('salario', models.CharField(max_length=400)),
                ('comentario5', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=400)),
                ('edad2', models.CharField(max_length=400)),
                ('parentesco', models.CharField(max_length=400)),
                ('ocupacion', models.CharField(max_length=400)),
                ('ingresoMensual', models.CharField(max_length=400)),
                ('lugarTrabajo', models.CharField(max_length=400)),
                ('ingresos', models.CharField(max_length=400)),
                ('salario2', models.CharField(max_length=400)),
                ('pension', models.CharField(max_length=400)),
                ('beca2', models.CharField(max_length=400)),
                ('gastos', models.CharField(max_length=400)),
                ('comida', models.CharField(max_length=400)),
                ('agua', models.CharField(max_length=400)),
                ('luz', models.CharField(max_length=400)),
                ('internetCable', models.CharField(max_length=400)),
                ('celular', models.CharField(max_length=400)),
                ('viaticos', models.CharField(max_length=400)),
                ('salud', models.CharField(max_length=400)),
                ('deudas', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, max_length=150, null=True)),
                ('sede', models.CharField(max_length=150)),
                ('cometario1', models.TextField(blank=True, null=True)),
                ('cometario2', models.TextField(blank=True, null=True)),
                ('cometario3', models.TextField(blank=True, null=True)),
                ('fechaExpediente', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
